export const environment = {
  production: false,
  envName: 'UAT',
  baseHref: '/portal/',
  apiUrl: 'https://itu7-apim.azure-api.net/uat-sofcheck-api/v1',
  apiPathPrefix: '/service/v1',
  workflowApiUrl:
    'https://itu7-apim.azure-api.net/uat-work-flow-api/v1/workflow',
  apiUsageCode: '',
  apiKey: 'a6adb39cb25e4975ad7fbc0a447afc15',
  version: '1.0.0',
  clientId: '8305ae0f-3152-49f8-8c3f-1ad24902bd47',
  authority: 'https://login.microsoftonline.com/common',
  redirectUrl: 'https://uat-sofcheck.ibpaas.com/portal/redirect',
  postLogoutRedirectUri: 'https://uat-sofcheck.ibpaas.com/portal/login',
  sofcBaseHerf: 'https://uat-sofcheck.ibpaas.com/portal',
  devLoginDisplay: 'true',
  storeRedirectUrlPrefix: 'https://uat.ibpaas.com/portal-store/redirect',
  storeEmbedTargetOrigin: 'https://uat.ibpaas.com/portal-store/myforms/embed',
};
